import { AudioPlayer, createAudioPlayer, setAudioModeAsync } from 'expo-audio';
import * as Speech from 'expo-speech';
import { GENERIC_LINE_KEYS } from '../content/lines';
import { SFX_ASSETS, VOICE_ASSETS } from './voiceAssets';

/**
 * All Spymaster audio ships as bundled mp3s generated by the ElevenLabs
 * pipeline (scripts/generate-voiceover.ts, spec section 6). Any line whose
 * mp3 hasn't been generated yet falls back to device text-to-speech, so
 * the batch can land incrementally. voiceAssets.ts is regenerated from the
 * files on disk by scripts/generate-voice-manifest.ts.
 */

let currentPlayer: AudioPlayer | null = null;
let audioModeReady = false;

async function ensureAudioMode(): Promise<void> {
  if (audioModeReady) return;
  audioModeReady = true;
  try {
    await setAudioModeAsync({ playsInSilentMode: true });
  } catch {
    // non-fatal: TTS still works
  }
}

export function stopSpeaking(): void {
  Speech.stop();
  if (currentPlayer) {
    try {
      currentPlayer.pause();
      currentPlayer.remove();
    } catch {
      // player may already be released
    }
    currentPlayer = null;
  }
}

/**
 * Speak a Spymaster line. Plays the bundled asset when the batch has
 * landed; otherwise falls back to TTS (slow and warm for small ears).
 */
export async function say(line: string, audioKey?: string): Promise<void> {
  await ensureAudioMode();
  stopSpeaking();

  const key = audioKey ?? GENERIC_LINE_KEYS[line];
  if (key && VOICE_ASSETS[key] !== undefined) {
    currentPlayer = createAudioPlayer(VOICE_ASSETS[key]);
    currentPlayer.play();
    return;
  }

  Speech.speak(line, { rate: 0.92, pitch: 1.0 });
}

/**
 * Fire a bundled sound effect (vault, correct chime, ...). Silent no-op
 * until the sfx batch is generated — haptics carry the feedback meanwhile.
 * Effects play on their own player so they never cut off the Spymaster.
 */
export function playSfx(key: string): void {
  const asset = SFX_ASSETS[key];
  if (asset === undefined) return;
  try {
    const player = createAudioPlayer(asset);
    player.play();
    setTimeout(() => {
      try { player.remove(); } catch {}
    }, 6000);
  } catch {
    // never let a sound effect break the game
  }
}

/** Play a parent-recorded message (or any local file) by uri. */
export async function playFile(uri: string): Promise<void> {
  await ensureAudioMode();
  stopSpeaking();
  currentPlayer = createAudioPlayer({ uri });
  currentPlayer.play();
}
