/**
 * GENERATED by scripts/generate-voice-manifest.ts — do not edit by hand.
 * 0 voice lines, 0 sound effects bundled.
 */

export const VOICE_ASSETS: Record<string, number> = {

};

export const SFX_ASSETS: Record<string, number> = {

};
