/**
 * Regenerates src/audio/voiceAssets.ts from whatever mp3s exist in
 * assets/vo/ and assets/sfx/. Run after generate-voiceover.ts.
 * Metro needs static require() calls, which is why this file is generated
 * rather than scanning at runtime.
 */
import { existsSync, readdirSync, writeFileSync } from 'fs';
import { join } from 'path';

const root = join(__dirname, '..');
const list = (dir: string): string[] =>
  existsSync(join(root, 'assets', dir))
    ? readdirSync(join(root, 'assets', dir)).filter((f) => f.endsWith('.mp3')).sort()
    : [];

const vo = list('vo');
const sfx = list('sfx');

const entry = (dir: string) => (f: string) =>
  `  ${JSON.stringify(f.replace(/\.mp3$/, ''))}: require('../../assets/${dir}/${f}'),`;

const out = `/**
 * GENERATED by scripts/generate-voice-manifest.ts — do not edit by hand.
 * ${vo.length} voice lines, ${sfx.length} sound effects bundled.
 */

export const VOICE_ASSETS: Record<string, number> = {
${vo.map(entry('vo')).join('\n')}
};

export const SFX_ASSETS: Record<string, number> = {
${sfx.map(entry('sfx')).join('\n')}
};
`;

writeFileSync(join(root, 'src', 'audio', 'voiceAssets.ts'), out);
console.log(`voiceAssets.ts: ${vo.length} voice lines, ${sfx.length} sfx`);
